# Generated by Django 2.0.2 on 2018-05-31 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('luffy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name_plural': '16:专题课程'},
        ),
    ]
